# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190122_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='订单唯一编号'),
        ),
    ]
