# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(max_length=200, upload_to='goods/images', verbose_name='商品轮播图片'),
        ),
    ]
