# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190115_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=200, upload_to='goods/images', verbose_name='首页轮播图片'),
        ),
        migrations.AlterField(
            model_name='categorybrand',
            name='image',
            field=models.ImageField(max_length=200, upload_to='brand/images', verbose_name='赞助图片'),
        ),
    ]
